#Algo1/Video/
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 1 - Why Study Algorithms - (4 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 2 - Integer Multiplication (9 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 3 - Karatsuba Multiplication (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 4 - About the Course (17 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 5 - Merge Sort- Motivation and Example (9 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 6 - Merge Sort- Pseudocode (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 7 - Merge Sort- Analysis (9 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/1 - 8 - Guiding Principles for Analysis of Algorithms (15 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 1 - Graph Search - Overview (23 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 2 - Breadth-First Search (BFS)- The Basics (14 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 3 - BFS and Shortest Paths (8 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 4 - BFS and Undirected Connectivity (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 5 - Depth-First Search (DFS)- The Basics (7 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 6 - Topological Sort (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 7 - Computing Strong Components- The Algorithm (29 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 8 - Computing Strong Components- The Analysis (26 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/10 - 9 - Structure of the Web [Optional] (19 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/11 - 1 - Dijkstra-'s Shortest-Path Algorithm (21 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/11 - 2 - Dijkstra-'s Algorithm- Examples (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/11 - 3 - Correctness of Dijkstra-'s Algorithm [Advanced - Optional] (19 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/11 - 4 - Dijkstra-'s Algorithm- Implementation and Running Time (26 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/12 - 1 - Data Structures- Overview (5 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/12 - 2 - Heaps- Operations and Applications (18 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/12 - 3 - Heaps- Implementation Details [Advanced - Optional] (21 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/13 - 1 - Balanced Search Trees- Operations and Applications (11 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/13 - 2 - Binary Search Tree Basics, Part I (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/13 - 3 - Binary Search Tree Basics, Part II (30 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/13 - 4 - Red-Black Trees (21 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/13 - 5 - Rotations [Advanced - Optional] (8 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/13 - 6 - Insertion in a Red-Black Tree [Advanced] (15 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/14 - 1 - Hash Tables- Operations and Applications (19 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/14 - 2 - Hash Tables- Implementation Details, Part I (19 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/14 - 3 - Hash Tables- Implementation Details, Part II (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/15 - 1 - Pathological Data Sets and Universal Hashing Motivation (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/15 - 2 - Universal Hashing- Definition and Example [Advanced - Optional] (26 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/15 - 3 - Universal Hashing- Analysis of Chaining [Advanced - Optional] (19 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/15 - 4 - Hash Table Performance with Open Addressing [Advanced - Optional] (16 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/16 - 1 - Bloom Filters- The Basics (16 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/16 - 2 - Bloom Filters- Heuristic Analysis (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/2 - 1 - The Gist (14 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/2 - 2 - Big-Oh Notation (4 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/2 - 3 - Basic Examples (7 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/2 - 4 - Big Omega and Theta (7 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/2 - 5 - Additional Examples [Review - Optional] (8 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/3 - 1 - O(n log n) Algorithm for Counting Inversions I (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/3 - 2 - O(n log n) Algorithm for Counting Inversions II (17 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/3 - 3 - Strassen-'s Subcubic Matrix Multiplication Algorithm (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/3 - 4 - O(n log n) Algorithm for Closest Pair I [Advanced - Optional] (32 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/3 - 5 - O(n log n) Algorithm for Closest Pair II [Advanced - Optional] (19 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/4 - 1 - Motivation (8 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/4 - 2 - Formal Statement (10 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/4 - 3 - Examples (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/4 - 4 - Proof I (10 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/4 - 5 - Interpretation of the 3 Cases (11 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/4 - 6 - Proof II (16 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/5 - 1 - Quicksort- Overview (12 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/5 - 2 - Partitioning Around a Pivot (25 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/5 - 3 - Correctness of Quicksort [Review - Optional] (11 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/5 - 4 - Choosing a Good Pivot (22min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/6 - 1 - Analysis I- A Decomposition Principle [Advanced - Optional] (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/6 - 2 - Analysis II- The Key Insight [Advanced - Optional] (12min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/6 - 3 - Analysis III- Final Calculations [Advanced - Optional] (9min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/7 - 1 - Part I [Review - Optional] (25 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/7 - 2 - Part II [Review - Optional] (17 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/8 - 1 - Randomized Selection - Algorithm (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/8 - 2 - Randomized Selection - Analysis (21 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/8 - 3 - Deterministic Selection - Algorithm [Advanced - Optional] (17 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/8 - 4 - Deterministic Selection - Analysis I [Advanced - Optional] (22 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/8 - 5 - Deterministic Selection - Analysis II [Advanced - Optional] (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/8 - 6 - Omega(n log n) Lower Bound for Comparison-Based Sorting [Advanced - Optional] (13 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/9 - 1 - Graphs and Minimum Cuts (16 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/9 - 2 - Graph Representations (14 min).mp4"
#wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/9 - 3 - Random Contraction Algorithm (9 min).mp4"
wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/9 - 4 - Analysis of Contraction Algorithm (30 min).mp4"
wget "https://s3-us-west-1.amazonaws.com/prod-edx/Algo1/Video/9 - 5 - Counting Minimum Cuts (7 min).mp4"
